# Generated by Django 5.2.17 on 2026-10-02 08:26

import crm.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("siteconfig", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=50, unique=True, verbose_name="name"),
                ),
            ],
            options={
                "verbose_name": "tag",
                "verbose_name_plural": "tags",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Coach",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(max_length=100, verbose_name="first name"),
                ),
                (
                    "last_name",
                    models.CharField(max_length=100, verbose_name="last name"),
                ),
                (
                    "email",
                    models.EmailField(blank=True, max_length=254, verbose_name="email"),
                ),
                (
                    "academy",
                    models.CharField(
                        blank=True,
                        help_text="Shown on the coach card, e.g. ALE or ADSAI.",
                        max_length=20,
                        verbose_name="academy",
                    ),
                ),
                (
                    "photo",
                    models.ImageField(
                        blank=True, upload_to="coaches/", verbose_name="photo"
                    ),
                ),
                ("background", models.TextField(blank=True, verbose_name="background")),
                (
                    "help_with",
                    models.TextField(blank=True, verbose_name="I can help you with"),
                ),
                (
                    "active",
                    models.BooleanField(
                        default=True,
                        help_text="Inactive coaches are hidden on the form and cannot be assigned.",
                        verbose_name="active",
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0, verbose_name="order")),
                (
                    "domains",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Used to warn when a graduation-track student would get a coach from their own domain.",
                        related_name="coaches",
                        to="siteconfig.domain",
                        verbose_name="home domains",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="coach",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="staff login",
                    ),
                ),
            ],
            options={
                "verbose_name": "coach",
                "verbose_name_plural": "coaches",
                "ordering": ["order", "first_name", "last_name"],
            },
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("message", models.CharField(max_length=300)),
                ("url", models.CharField(blank=True, max_length=300)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("read_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Startup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        help_text="Staff only. Leave empty until the startup has a name.",
                        max_length=200,
                        verbose_name="startup name",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        validators=[crm.validators.MaxWordsValidator(200)],
                        verbose_name="business (idea) description",
                    ),
                ),
                (
                    "has_paying_customers",
                    models.BooleanField(
                        blank=True, null=True, verbose_name="has paying customers"
                    ),
                ),
                (
                    "idea_validated",
                    models.BooleanField(
                        blank=True,
                        null=True,
                        verbose_name="idea validated with target customers",
                    ),
                ),
                (
                    "goals",
                    models.TextField(
                        blank=True, verbose_name="goals for the coach track"
                    ),
                ),
                (
                    "kvk_number",
                    models.CharField(
                        blank=True, max_length=8, verbose_name="KvK number"
                    ),
                ),
                (
                    "archived_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="archived at"
                    ),
                ),
                (
                    "last_activity_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last activity"
                    ),
                ),
                (
                    "assigned_coach",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="startups",
                        to="crm.coach",
                        verbose_name="assigned coach",
                    ),
                ),
                (
                    "stage",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="startups",
                        to="siteconfig.pipelinestage",
                        verbose_name="stage",
                    ),
                ),
            ],
            options={
                "verbose_name": "startup / idea",
                "verbose_name_plural": "startups / ideas",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Founder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(blank=True, max_length=100, verbose_name="role"),
                ),
                (
                    "joined_on",
                    models.DateField(
                        default=django.utils.timezone.localdate,
                        verbose_name="joined on",
                    ),
                ),
                (
                    "startup",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="founder_links",
                        to="crm.startup",
                    ),
                ),
            ],
            options={
                "verbose_name": "founder",
                "verbose_name_plural": "founders",
            },
        ),
        migrations.CreateModel(
            name="Activity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("note", "Note"),
                            ("meeting", "Meeting"),
                            ("email", "Email"),
                            ("event", "Event attendance"),
                            ("referral", "Referral"),
                            ("intake", "Intake"),
                        ],
                        default="note",
                        max_length=10,
                        verbose_name="type",
                    ),
                ),
                (
                    "date",
                    models.DateField(
                        default=django.utils.timezone.localdate, verbose_name="date"
                    ),
                ),
                ("body", models.TextField(verbose_name="details")),
                (
                    "admin_only",
                    models.BooleanField(
                        default=False, verbose_name="visible to admins only"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "author",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="activities",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="author",
                    ),
                ),
                (
                    "startup",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activities",
                        to="crm.startup",
                        verbose_name="startup",
                    ),
                ),
            ],
            options={
                "verbose_name": "activity",
                "verbose_name_plural": "activities",
                "ordering": ["-date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "first_name",
                    models.CharField(max_length=100, verbose_name="first name"),
                ),
                (
                    "last_name",
                    models.CharField(max_length=100, verbose_name="last name"),
                ),
                (
                    "student_number",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=6,
                        validators=[crm.validators.validate_student_number],
                        verbose_name="student number",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        db_index=True, max_length=254, verbose_name="email"
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        max_length=20,
                        validators=[crm.validators.validate_phone],
                        verbose_name="phone number",
                    ),
                ),
                (
                    "archived_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="archived at"
                    ),
                ),
                (
                    "anonymised_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="anonymised at"
                    ),
                ),
                (
                    "domain",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="students",
                        to="siteconfig.domain",
                        verbose_name="domain",
                    ),
                ),
                (
                    "merged_into",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="merged_from",
                        to="crm.student",
                        verbose_name="merged into",
                    ),
                ),
                (
                    "study_year",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="students",
                        to="siteconfig.studyyear",
                        verbose_name="study year",
                    ),
                ),
            ],
            options={
                "verbose_name": "student",
                "verbose_name_plural": "students",
                "ordering": ["last_name", "first_name"],
            },
        ),
        migrations.AddField(
            model_name="startup",
            name="founders",
            field=models.ManyToManyField(
                related_name="startups",
                through="crm.Founder",
                to="crm.student",
                verbose_name="founders",
            ),
        ),
        migrations.CreateModel(
            name="Registration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "submitted_at",
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        verbose_name="submitted at",
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("form", "Registration form"),
                            ("walk_in", "Walk-in (added by staff)"),
                            ("import", "Microsoft Forms import"),
                        ],
                        default="form",
                        max_length=10,
                        verbose_name="source",
                    ),
                ),
                ("comments", models.TextField(blank=True, verbose_name="comments")),
                (
                    "answers",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="answers as submitted"
                    ),
                ),
                (
                    "consent_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="privacy consent given at"
                    ),
                ),
                (
                    "forms_response_id",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        unique=True,
                        verbose_name="Microsoft Forms response ID",
                    ),
                ),
                (
                    "is_duplicate_student",
                    models.BooleanField(
                        default=False, verbose_name="matched an existing student"
                    ),
                ),
                (
                    "intake_deadline",
                    models.DateField(
                        blank=True,
                        db_index=True,
                        null=True,
                        verbose_name="intake deadline",
                    ),
                ),
                (
                    "intake_scheduled_on",
                    models.DateField(
                        blank=True,
                        help_text="The date the intake was arranged; this stops the 10-working-day clock.",
                        null=True,
                        verbose_name="intake scheduled on",
                    ),
                ),
                (
                    "intake_held_on",
                    models.DateField(
                        blank=True, null=True, verbose_name="intake held on"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="created by",
                    ),
                ),
                (
                    "intake_coach",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="intakes",
                        to="crm.coach",
                        verbose_name="intake held by",
                    ),
                ),
                (
                    "preferred_coach",
                    models.ForeignKey(
                        blank=True,
                        help_text="Empty = no preference.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="preferred_by",
                        to="crm.coach",
                        verbose_name="preferred coach",
                    ),
                ),
                (
                    "privacy_statement",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="siteconfig.privacystatement",
                        verbose_name="privacy statement version",
                    ),
                ),
                (
                    "startup",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="registrations",
                        to="crm.startup",
                        verbose_name="startup / idea",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="registrations",
                        to="crm.student",
                        verbose_name="student",
                    ),
                ),
            ],
            options={
                "verbose_name": "registration",
                "verbose_name_plural": "registrations",
                "ordering": ["-submitted_at"],
            },
        ),
        migrations.CreateModel(
            name="GraduationTrack",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "approval",
                    models.CharField(
                        choices=[("yes", "Yes"), ("not_yet", "No, not yet")],
                        max_length=10,
                        verbose_name="programme approval to graduate with own company",
                    ),
                ),
                (
                    "topic",
                    models.TextField(
                        validators=[crm.validators.MaxWordsValidator(100)],
                        verbose_name="graduation assignment topic",
                    ),
                ),
                (
                    "supervisor_name",
                    models.CharField(
                        max_length=200, verbose_name="graduation supervisor"
                    ),
                ),
                (
                    "hand_in_date",
                    models.DateField(
                        verbose_name="intended hand-in date of final product"
                    ),
                ),
                (
                    "registration",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="graduation",
                        to="crm.registration",
                    ),
                ),
                (
                    "startup",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="graduation_tracks",
                        to="crm.startup",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="graduation_tracks",
                        to="crm.student",
                    ),
                ),
            ],
            options={
                "verbose_name": "graduation track",
                "verbose_name_plural": "graduation tracks",
                "ordering": ["hand_in_date"],
            },
        ),
        migrations.AddField(
            model_name="founder",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="founder_links",
                to="crm.student",
            ),
        ),
        migrations.CreateModel(
            name="FollowUp",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="title")),
                ("notes", models.TextField(blank=True, verbose_name="notes")),
                ("due_date", models.DateField(db_index=True, verbose_name="due date")),
                (
                    "auto_reason",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        verbose_name="created automatically because",
                    ),
                ),
                (
                    "done_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="done at"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="follow_ups",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="assigned to",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="created by",
                    ),
                ),
                (
                    "startup",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="follow_ups",
                        to="crm.startup",
                        verbose_name="startup",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="follow_ups",
                        to="crm.student",
                        verbose_name="student",
                    ),
                ),
            ],
            options={
                "verbose_name": "follow-up",
                "verbose_name_plural": "follow-ups",
                "ordering": ["due_date"],
            },
        ),
        migrations.AddField(
            model_name="startup",
            name="tags",
            field=models.ManyToManyField(
                blank=True, related_name="startups", to="crm.tag", verbose_name="tags"
            ),
        ),
        migrations.AddConstraint(
            model_name="founder",
            constraint=models.UniqueConstraint(
                fields=("startup", "student"), name="unique_founder"
            ),
        ),
    ]
