# Generated by Django 5.2.17 on 2026-10-02 08:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="OutgoingEmail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("kind", models.CharField(max_length=50, verbose_name="email")),
                ("to", models.CharField(max_length=254, verbose_name="to")),
                ("subject", models.CharField(max_length=255, verbose_name="subject")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("sent", "Sent"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=10,
                        verbose_name="status",
                    ),
                ),
                ("error", models.TextField(blank=True, verbose_name="error")),
                (
                    "attempts",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="attempts"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "sent_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="sent at"),
                ),
                (
                    "registration",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="emails",
                        to="crm.registration",
                        verbose_name="registration",
                    ),
                ),
            ],
            options={
                "verbose_name": "sent email",
                "verbose_name_plural": "sent emails",
                "ordering": ["-created_at"],
            },
        ),
    ]
