# Generated by Django 5.2.17 on 2026-10-02 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0002_emails"),
    ]

    operations = [
        migrations.AddField(
            model_name="registration",
            name="intake_planned_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When the intake chat will take place.",
                null=True,
                verbose_name="intake planned for",
            ),
        ),
    ]
