# Generated by Django 5.2.17 on 2026-10-02 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0003_intake_planned_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="activity",
            name="kind",
            field=models.CharField(
                choices=[
                    ("note", "Note"),
                    ("meeting", "Meeting"),
                    ("email", "Email"),
                    ("event", "Event attendance"),
                    ("referral", "Referral"),
                    ("intake", "Intake"),
                    ("stage", "Stage change"),
                ],
                default="note",
                max_length=10,
                verbose_name="type",
            ),
        ),
    ]
