# Generated by Django 5.2.17 on 2026-10-05 08:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0004_activity_stage_kind"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ExportLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("kind", models.CharField(max_length=30, verbose_name="list")),
                ("file_format", models.CharField(max_length=10, verbose_name="format")),
                (
                    "filters",
                    models.JSONField(blank=True, default=dict, verbose_name="filters"),
                ),
                ("row_count", models.PositiveIntegerField(verbose_name="rows")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="exported at"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="exported by",
                    ),
                ),
            ],
            options={
                "verbose_name": "export",
                "verbose_name_plural": "exports",
                "ordering": ["-created_at"],
            },
        ),
    ]
