# Generated by Django 5.2.17 on 2026-10-05 09:01

import crm.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0005_export_log"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="registration",
            name="submitted_at_estimated",
            field=models.BooleanField(
                default=False,
                help_text="Imported without a real registration date; left out of the monthly figures.",
                verbose_name="registration date estimated",
            ),
        ),
        migrations.AlterField(
            model_name="registration",
            name="forms_response_id",
            field=models.CharField(
                blank=True,
                help_text="Microsoft Forms response ID or spreadsheet row key; prevents importing the same row twice.",
                max_length=120,
                null=True,
                unique=True,
                verbose_name="import reference",
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="email",
            field=models.EmailField(
                blank=True, db_index=True, max_length=254, verbose_name="email"
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="phone",
            field=models.CharField(
                blank=True,
                max_length=20,
                validators=[crm.validators.validate_phone],
                verbose_name="phone number",
            ),
        ),
        migrations.CreateModel(
            name="ImportBatch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("filename", models.CharField(max_length=200)),
                (
                    "file_data",
                    models.BinaryField(
                        blank=True,
                        help_text="The uploaded file, kept only until a sheet is chosen.",
                        null=True,
                    ),
                ),
                ("sheet", models.CharField(blank=True, max_length=100)),
                ("header", models.JSONField(default=list)),
                (
                    "rows",
                    models.JSONField(
                        default=list,
                        help_text="Parsed rows; cleared after import (personal data).",
                    ),
                ),
                ("mapping", models.JSONField(blank=True, default=dict)),
                (
                    "status",
                    models.CharField(
                        choices=[("uploaded", "Uploaded"), ("imported", "Imported")],
                        default="uploaded",
                        max_length=10,
                    ),
                ),
                ("result", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("imported_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "import",
                "verbose_name_plural": "imports",
                "ordering": ["-created_at"],
            },
        ),
    ]
