# Generated by Django 5.2.17 on 2026-10-05 09:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0006_imports"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PrivacyAction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("export", "Data export"),
                            ("anonymise", "Anonymised"),
                            ("delete", "Deleted"),
                        ],
                        max_length=10,
                        verbose_name="action",
                    ),
                ),
                ("student_ref", models.PositiveIntegerField(verbose_name="student ID")),
                (
                    "reason",
                    models.CharField(
                        blank=True,
                        help_text="No personal data, e.g. “request by student” or “retention period passed”.",
                        max_length=200,
                        verbose_name="reason",
                    ),
                ),
                (
                    "details",
                    models.JSONField(blank=True, default=dict, verbose_name="details"),
                ),
                (
                    "performed_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="at"),
                ),
                (
                    "performed_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="by",
                    ),
                ),
            ],
            options={
                "verbose_name": "privacy action",
                "verbose_name_plural": "privacy actions",
                "ordering": ["-performed_at"],
            },
        ),
    ]
