# Generated by Django 5.2.17 on 2026-10-02 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AppSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "intake_working_days",
                    models.PositiveSmallIntegerField(
                        default=10, verbose_name="intake within (working days)"
                    ),
                ),
                (
                    "intake_due_soon_days",
                    models.PositiveSmallIntegerField(
                        default=2,
                        verbose_name="highlight when due within (working days)",
                    ),
                ),
                (
                    "staff_notification_mode",
                    models.CharField(
                        choices=[
                            ("email", "Email"),
                            ("in_app", "In-app"),
                            ("both", "Email and in-app"),
                        ],
                        default="both",
                        max_length=10,
                        verbose_name="new registration notifications",
                    ),
                ),
                (
                    "staff_notification_email",
                    models.EmailField(
                        default="buss-placeholder@example.org",
                        max_length=254,
                        verbose_name="staff notification address",
                    ),
                ),
                (
                    "retention_years",
                    models.PositiveSmallIntegerField(
                        default=2,
                        verbose_name="flag for anonymisation after (years inactive or alumni)",
                    ),
                ),
                (
                    "inactivity_weeks",
                    models.PositiveSmallIntegerField(
                        default=6, verbose_name="dashboard: no activity for (weeks)"
                    ),
                ),
                (
                    "rate_limit_per_hour",
                    models.PositiveSmallIntegerField(
                        default=5, verbose_name="max registrations per hour per IP"
                    ),
                ),
            ],
            options={
                "verbose_name": "app settings",
                "verbose_name_plural": "app settings",
            },
        ),
        migrations.CreateModel(
            name="ClosureDay",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(unique=True, verbose_name="date")),
                ("name", models.CharField(max_length=100, verbose_name="name")),
            ],
            options={
                "verbose_name": "closure day",
                "verbose_name_plural": "closure days",
                "ordering": ["date"],
            },
        ),
        migrations.CreateModel(
            name="Domain",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, unique=True, verbose_name="name"),
                ),
                ("order", models.PositiveIntegerField(default=0, verbose_name="order")),
                (
                    "active",
                    models.BooleanField(
                        default=True,
                        help_text="Inactive options are hidden on the form but kept on existing records.",
                        verbose_name="active",
                    ),
                ),
                (
                    "academy_code",
                    models.CharField(
                        blank=True,
                        help_text="e.g. ALE, AFT, HFM, AGM, BE, LOG, ADSAI",
                        max_length=10,
                        verbose_name="academy code",
                    ),
                ),
                (
                    "is_employee",
                    models.BooleanField(
                        default=False, verbose_name="is the 'I am an employee' option"
                    ),
                ),
            ],
            options={
                "verbose_name": "domain",
                "verbose_name_plural": "domains",
                "ordering": ["order", "name"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="PipelineStage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, unique=True, verbose_name="name"),
                ),
                ("order", models.PositiveIntegerField(default=0, verbose_name="order")),
                (
                    "active",
                    models.BooleanField(
                        default=True,
                        help_text="Inactive options are hidden on the form but kept on existing records.",
                        verbose_name="active",
                    ),
                ),
                (
                    "colour",
                    models.CharField(
                        default="#6b7280",
                        help_text="Hex colour, e.g. #e8730c",
                        max_length=7,
                        verbose_name="colour",
                    ),
                ),
                (
                    "is_initial",
                    models.BooleanField(
                        default=False,
                        verbose_name="initial stage for new registrations",
                    ),
                ),
                (
                    "is_closed",
                    models.BooleanField(
                        default=False,
                        help_text="e.g. Alumni / Stopped: no longer counted as active caseload.",
                        verbose_name="closed stage",
                    ),
                ),
                (
                    "marks_intake_scheduled",
                    models.BooleanField(
                        default=False,
                        verbose_name="moving here means the intake is scheduled",
                    ),
                ),
                (
                    "marks_intake_done",
                    models.BooleanField(
                        default=False,
                        verbose_name="moving here means the intake is done",
                    ),
                ),
            ],
            options={
                "verbose_name": "pipeline stage",
                "verbose_name_plural": "pipeline stages",
                "ordering": ["order", "name"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="PrivacyStatement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "version",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="version"
                    ),
                ),
                ("body", models.TextField(verbose_name="body")),
                (
                    "published_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Leave empty while drafting. The latest published version is shown on the form.",
                        null=True,
                        verbose_name="published at",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "privacy statement",
                "verbose_name_plural": "privacy statements",
                "ordering": ["-published_at", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SiteText",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "key",
                    models.SlugField(max_length=60, unique=True, verbose_name="key"),
                ),
                (
                    "title",
                    models.CharField(blank=True, max_length=200, verbose_name="title"),
                ),
                (
                    "body",
                    models.TextField(
                        blank=True,
                        help_text="Plain text; blank lines start a new paragraph, lines starting with '- ' become a list.",
                        verbose_name="body",
                    ),
                ),
                (
                    "help",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        verbose_name="where this text is used",
                    ),
                ),
            ],
            options={
                "verbose_name": "page text",
                "verbose_name_plural": "page texts",
                "ordering": ["key"],
            },
        ),
        migrations.CreateModel(
            name="StudyYear",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, unique=True, verbose_name="name"),
                ),
                ("order", models.PositiveIntegerField(default=0, verbose_name="order")),
                (
                    "active",
                    models.BooleanField(
                        default=True,
                        help_text="Inactive options are hidden on the form but kept on existing records.",
                        verbose_name="active",
                    ),
                ),
                (
                    "is_graduation_track",
                    models.BooleanField(
                        default=False,
                        help_text="Choosing this option shows the graduation section on the form.",
                        verbose_name="graduating within own company",
                    ),
                ),
            ],
            options={
                "verbose_name": "study year",
                "verbose_name_plural": "study years",
                "ordering": ["order", "name"],
                "abstract": False,
            },
        ),
    ]
