# Generated by Django 5.2.17 on 2026-10-02 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("siteconfig", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appsettings",
            name="staff_notification_email",
            field=models.EmailField(
                default="startupsupport@buas.nl",
                max_length=254,
                verbose_name="staff notification address",
            ),
        ),
    ]
