# Generated by Django 5.2.17 on 2026-10-02 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("siteconfig", "0002_staff_email_default"),
    ]

    operations = [
        migrations.CreateModel(
            name="Partner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, unique=True, verbose_name="name"),
                ),
                (
                    "logo",
                    models.ImageField(
                        blank=True,
                        help_text="PNG or SVG with a transparent background works best.",
                        upload_to="partners/",
                        verbose_name="logo",
                    ),
                ),
                ("url", models.URLField(blank=True, verbose_name="website")),
                (
                    "active",
                    models.BooleanField(
                        default=True, verbose_name="show on public pages"
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0, verbose_name="order")),
            ],
            options={
                "verbose_name": "partner",
                "verbose_name_plural": "partners",
                "ordering": ["order", "name"],
            },
        ),
    ]
