# Generated by Django 5.2.17 on 2026-10-02 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("siteconfig", "0003_partner"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmailTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "key",
                    models.CharField(
                        choices=[
                            (
                                "registration_confirmation",
                                "Confirmation to the student",
                            ),
                            (
                                "staff_new_registration",
                                "New registration, to BUSS staff",
                            ),
                        ],
                        max_length=50,
                        verbose_name="email",
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        choices=[("en", "English"), ("nl", "Dutch")],
                        default="en",
                        max_length=10,
                        verbose_name="language",
                    ),
                ),
                ("subject", models.CharField(max_length=200, verbose_name="subject")),
                (
                    "body",
                    models.TextField(
                        help_text="Plain text. Blank lines start a new paragraph; lines starting with '- ' become a list.",
                        verbose_name="text",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "email template",
                "verbose_name_plural": "email templates",
                "ordering": ["key", "language"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("key", "language"), name="unique_email_template"
                    )
                ],
            },
        ),
    ]
